
spring:
  application:
    name: phone-book
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
